### ISSUE TITLE
Strange crash when adding img/audio pair to trial type

### ISSUE THREAD

**Issue by jfkominsky** [jfkominsky/PyHab#24]
Add image/audio pair to stimulus library in an experiment with only one trial type. If you then try to immediately add it to the trial type, it freezes while trying to pull up the list of trials. If you do anything else in between, like add a thing to the study flow or create a new trial type, it seems to be fine.

QTgui issue?

**Comment by kzelish** [comment]
Hi @jfkominsky 

Thank you for designing pyhab for non-coder people. 
I'm writing to let you know this issue still goes in pyhab. Did you fix it? I did not see your answer above. 
Thank you.
Best wishes,
Zehra

**Comment by jfkominsky** [comment]
Hi @kzelish , I'm afraid I have not found a fix for this yet but I am still looking into it. In the interim, the easiest way to work around it is to add and then remove another instance of the trial type from the study flow before associating the stimulus with the trial type.

**Comment by kzelish** [comment]
Thank you for your response @jfkominsky. Apologies, but I am a little confused about what I should do. You mean I should create a dummy trial and add stimulus (an image with audio), then remove it from the study flow.  
Could you elaborate on that if it's possible, please? Thanks.

**Comment by jfkominsky** [comment]
Add a trial to the study flow by clicking on it in the palette on the right, then click the trial in the study flow and click the "remove" button that appears. You are just doing and undoing an arbitrary action, but for whatever reason that usually makes it so that adding the stimulus type to the trial will now work.

**Comment by kzelish** [comment]
Thank you for your detailed explanation. All clear now.
Apologies to bother you.

Best wishes,
Zehra
________________________________

**Comment by jfkominsky** [comment]
WIth PsychoPy 2023.2.0 using the new pyqt5 library, this should be fixed.

**Comment by kzelish** [comment]
Thanks for the update.
Best,
Zehra

From: jfkominsky ***@***.***>
Date: Friday, 4 August 2023 at 08:24
To: jfkominsky/PyHab ***@***.***>
Cc: Zehra Karademir ***@***.***>, Mention ***@***.***>
Subject: Re: [jfkominsky/PyHab] Strange crash when adding img/audio pair to trial type (#24)

WIth PsychoPy 2023.2.0 using the new pyqt5 library, this should be fixed.
