### ISSUE TITLE
Stimuli Setting issue - 'AttributeError: module 'pyglet.window' has no attribute 'get_platform'.

### ISSUE THREAD

**Issue by kzelish** [jfkominsky/PyHab#30]
Hi @jfkominsky 

I use pyhab to build a head-turn preference experiment, but it crashed when I try to open the stimuli setting window. I had this problem when I upgraded BigSure before it was fine. 

It says there is 'AttributeError: module 'pyglet.window' has no attribute 'get_platform'. I searched it online but did not find [anything](url) useful.

File "/Applications/PyHab-0.8.2/PyHab/PyHabBuilder.py", line 1725, in stimSettingsDlg
    defDisp = pyglet.window.get_platform().get_default_display()
AttributeError: module 'pyglet.window' has no attribute 'get_platform'
##### Experiment ended. #####

Could you please let me know how I can solve this issue?

Many thanks.
Best,
Zehra

**Comment by jfkominsky** [comment]
Hi @kzelish, this is not an issue with PyHab, this is an issue with the PsychoPy installation on your computer. Are you using the PsychoPy standalone app or running directly through Python? If you are using the standalone app, make sure you update to the latest version (2020.1.4). If you are using a different Python environment, you may need to downgrade your Pyglet version, see https://discourse.psychopy.org/t/error-module-pyglet-window-has-no-attribute-get-platform-fixed-solution-below/8897 and https://discourse.psychopy.org/t/visual-window-error/8578/3

I hope that helps!

**Comment by kzelish** [comment]
Thank you very much for your reply.

Yes, I use the latest version of PsychoPy. After your email, I deleted PsychoPy and re-installed it again.

I'm afraid it still does not work. I assume the BigSur update crashed everything. Fortunately, I do not have this issue in the Lab PC.

Thank you for attaching useful links; I need to solve my PC's pyglet issue.

Many thanks!
Best wishes,
Zehra
________________________________
