### ISSUE TITLE
endAttnGetter vs. startTrial in Online Studies

### ISSUE THREAD

**Issue by sammaione** [jfkominsky/PyHab#54]
Hello!

We are running an online study, and I am a little confused about the trialTiming.csv output. Of the four event conditions, "startAttnGetter", "endAttnGetter", "startTrial", and "endTrial", the event condition "endAttnGetter" seems to match up consistently with the start of the trial (or in other words, immediately after the attention getter ends, which is immediately a trial). This is fine, but what does "startTrial" constitute then? In most trials, the difference is only half a second, but for our first trial (our calibration trial), there is a stark 3 second difference between "endAttnGetter" and "startTrial". An example is shown below:

```
trialNum,trialType,event,time
1,calibration-short,startAttnGetter,0.02680308325216174
1,calibration-short,endAttnGetter,3.560075916815549
1,calibration-short,startTrial,6.960292249917984
1,calibration-short,endTrial,25.966494167223573
2,train,startAttnGetter,26.983967083040625
2,train,endAttnGetter,30.07727766688913
2,train,startTrial,30.693748833145946
2,train,endTrial,69.93557758303359
```

Thank you for the help--still pretty new to PyHab so any help is very much appreciated!

Sam

**Comment by jfkominsky** [comment]
On trials that do not auto-advance, the trial is not considered to have "started" until the first gaze-on event. So, this could be a case where the attention-getter ended and then there was a three-second pause until the first "gaze-on" key was pressed. That would be the most likely cause. If that doesn't fit the way this trial is set up, let me know and I can look into it further.

**Comment by sammaione** [comment]
This makes sense -- thank you for the information! Much appreciated.
